### ISSUE TITLE
Profile - Final Checklist

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#139]
## Description
Creating this checklist to track the progress for each of the profile's tabs.

## Checklist | Status

- [x] [Profile Sticky](https://github.com/colonistio/design/issues/152) | Done
- [x] [Overview](https://github.com/colonistio/design/issues/163) | Sent a submission
- [x] [Ranked](https://github.com/colonistio/design/issues/151) | Done
- [x] [History ](https://github.com/colonistio/design/issues/162) | Desktop Ver. Done
- [x] [Items](https://github.com/colonistio/design/issues/149) | Done 
- [x] [Friends](https://github.com/colonistio/design/issues/144)| Done - Being Implemented
- [x] [Membership ](https://github.com/colonistio/design/issues/143) | Done
## Resource
- https://github.com/colonistio/design/issues/2

## Reviewer

@goktugyil
