### ISSUE TITLE
Game Board Actions Checklist

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#315]
## Goal
- Revamped existing gameboard UI by removing some action buttons and letting the players interact on the board more.
- [Excel Checklist](https://docs.google.com/spreadsheets/d/1GX_6zr_wbwa6Nsn6ScmDIjK9otVCN1Sw8gCkuY1Gy3U/edit#gid=93531664)

# Locations on the map being tapped by player
### Any empty tile corner spot
- [x] If the spot is a valid building location and the player has the resources needed to place it, and available settlements, show the option to build a settlement.
- [x] If the spot is a valid building location but the player does not have the necessary resources to build it, show a grayed out settlement icon.
- [x] ~If the spot is not a valid building location because it's too close to other buildings, show a bouncing red circle for 1 second.~ (I did not do this, we don't need to show a selector so there's no need to add to the visual complexity)
- [x] If the player cannot place the settlement because their are out of settlement pieces to play, show the grayed out settlement icon.
- [x] If the spot is not a valid building location because the player does not have connecting roads, nothing happens.

### Tile corner containing settlement belonging to the player doing the action
- [x] If the player has the resources needed to place it, show the option to build a city.
- [x] If player does not have the necessary resources to build it, show a grayed out city icon.

### Tile corner containing city belonging to the player doing the action
- [x] There are no interactions for this case that will be done directly from the map, so the city icon subtly wobbles in scale for 2 seconds, as in oscillates between growing in size and getting smaller about 3 times until it reverts to its default state.

### Any tile corner where an opponent has built any building
- [x] There are no interactions for this case that will be done directly from the map, so whatever element has been tapped, it will subtly wobble in scale for 2 seconds, as in oscillates between growing in size and getting smaller about 3 times until it reverts to its default state.

### Any empty tile edge
- [ ] If the edge is a valid building location because it meets all of the below criteria:
     - [x] 1. it's adjacent to at least one road belonging to the player through a tile corner that is free of any opponent buildings OR the edge is adjacent to a player owned building
     - [x] 2. the player has enough resources to place the road
     - [ ] 3. the tile edge belongs to a land tile as opposed to sea tile
Then, show the option to build a road.
- If the spot does not meet criteria 1, nothing happens.
- If the spot does not meet criteria 2, show a grayed out road icon
- If the spot does not meet criteria 3, nothing happens.

### Tile edge containing  road/trade route belonging to the player doing the action
- [x] For roads here are no interactions that will be done directly from the map, the road icon subtly wobble in scale for 2 seconds, as in oscillates between growing in size and getting smaller about 3 times until it reverts to its default state.

### Any tile edge where an opponent has built anything
- [x] ~There are no interactions for other player's buildings that can be done directly though map interaction, so whatever element has been tapped, it will subtly wobble in scale for 2 seconds, as in oscillate between growing in size and getting smaller about 3 times until it reverts to its default state.~ (similar to `any tile corner has built any building`)

### Tile center containing robber or pirate ship
- [ ] The players will not activate the robber from the map, they will use devcards or 7rolls to activate him instead. 
- [ ] Once the robber is activated player will tap on the tile where they want to place him same as in the pervious web design.

=====================================================================================

### Any empty tile corner spot
- [ ] same with Base
### Tile corner containing settlement belonging to the player doing the action
- [ ] same with Base
### Tile corner containing city belonging to the player doing the action
- [ ] Since in the Seafarers game there is nothing to build on top of city, the city icon subtly wobbles in scale for 2 seconds, as in oscillates between growing in size and getting smaller about 3 times until it reverts to its default state.
### Any tile corner where an opponent has built any building
- [ ] same with Base
### Any empty tile edge
- [ ] For trade routes, we have the same behaviour as for roads in the base game, with the exception that they must be on the edge of the sea tile instead of land tile. Other than that, just replace "road" with "trade route" from the design description of the base game. 
- [ ] The road and trade routes are not mutually exclusive, both build options can be shown for cases where tile edges that are taped are between a land title and a sea tile.
### Tile edge containing road/trade route belonging to the player doing the action
- [ ] Trade routes/ships work same as in the previous design, the player can tap one of them per turn that is not part of a closed loop and then select another edge to place them on (if the pirate ship is not present).
### Any tile edge where an opponent has built anything
- [ ] same with Base
### Tile center containing robber or pirate ship
- [ ] Same as for the base game but also applies to pirate ship.
